---
title: "Лабораторная работа №1. Введение в язык обработки данных R. Визуализация данных"
mainfont: Arial
monofont: Consolas
output:
  pdf_document: 
    latex_engine: lualatex
# Перед верстанием отчёта настоятельно рекомендуется изменить параметры. Более подробная информация по ним представлена в комментариях ниже.
params: 
    surname: "Dubovskij"
    name: "Jan"
    variant: "14"
    filename: "f.txt"
---

<!-- Ниже расположены два блока с программным кодом, который выводит фамилию и имя студента, а также номер варианта. Они определяются параметрами surname, name и variant, объявленными в преамбуле, расположенной выше. К параметрам в коде можно обращаться через конструкцию params$var, где var - название переменной --> 

<!-- Значения этих параметров можно поменять непосредственно в самом файле или используя опцию "Knit with Parameters..." -->

<!-- Параметр echo=FALSE означает, что в отчёте сам код представлен не будет, будет выведен только результат его выполнения (в данном случае - вывод имени студента и номера варианта) -->

**Студент:**

```{r, echo=FALSE}
cat(params$surname, params$name)
```

**Вариант**

```{r, echo=FALSE}
cat(params$variant)
```

## Чтение данных из файла

<!-- В коде ниже используется переменная params$filename, определённая в преамбуле. Можно её переопределить прямо в этом файле либо сверстать отчёт при помощи команды "Knit with Parameters...", указав в соответствующем поле имя файла или путь к нему. -->

<!-- В зависимости от структуры Вашего файла может понадобиться отредактировать код ниже -->

```{r}
dat <- read.table(file=params$filename, dec=".")
dat
```

## Формирование таблицы

<!-- Для выполнения этого задания в области ниже напишите код, который строит дискретный вариационный ряд и рассчитывает его частотные характеристики. В конце нужно вывести саму таблицу. -->

```{r}
d<-dat[,1]
a<-table(dat)
f<-as.data.frame(a)
f[,3]<-100*a/(sum(a))
f[,4]<-cumsum(a)
f[,5]<-cumsum(f[,3])
colnames(f)<-c("значение","частота","частость","накопленная частота","накопленная частость")
f
```

## Построение графиков

Полигон частот

```{r dev=c('png')}
plot(a,type="l",main="Полигон частот",xlab="значение",ylab="частота")

```

Кумуляты абсолютных и относительных частот

```{r dev=c('png')}
v<-sort(d)
x<-unique(v)
y<-as.numeric(f[,4])
plot(x,y,type="l",xlab="значение",ylab="накопленная частота",main="кумулята абсолютных частот")
z<-as.numeric(f[,5]/f[24,5])
plot(x,z,type="l",xlab="значение",ylab="накопленная частота", main= "кумулята относительных частот")
```