public final class java.lang.Integer extends java.lang.Number
{
 public java.lang.Integer(java.lang.String);
 public java.lang.Integer(int);

 public static int numberOfLeadingZeros(int);
 public static int numberOfTrailingZeros(int);
 public static int bitCount(int);
 public boolean equals(java.lang.Object);
 public static java.lang.String toString(int);
 public java.lang.String toString();
 public static java.lang.String toString(int, int);
 public static int hashCode(int);
 public int hashCode();
 public static int min(int, int);
 public static int max(int, int);
 public static int signum(int);
 public static int expand(int, int);
 public static int divideUnsigned(int, int);
 public static int remainderUnsigned(int, int);
 public static int reverseBytes(int);
 public static int compress(int, int);
 static int getChars(int, int, [B);
 public volatile int compareTo(java.lang.Object);
 public int compareTo(java.lang.Integer);
 public static int compare(int, int);
 public byte byteValue();
 public short shortValue();
 public int intValue();
 public long longValue();
 public float floatValue();
 public double doubleValue();
 public static java.lang.Integer valueOf(int);
 public static java.lang.Integer valueOf(java.lang.String, int);
 public static java.lang.Integer valueOf(java.lang.String);
 public static java.lang.String toHexString(int);
 public static java.lang.Integer decode(java.lang.String);
 public java.lang.Integer resolveConstantDesc(java.lang.invoke.MethodHandles$Lookup);
 public volatile java.lang.Object resolveConstantDesc(java.lang.invoke.MethodHandles$Lookup);
 public java.util.Optional describeConstable();
 public static int parseInt(java.lang.String, int);
 public static int parseInt(java.lang.String);
 public static int parseInt(java.lang.CharSequence, int, int, int);
 public static int reverse(int);
 static int stringSize(int);
 public static long toUnsignedLong(int);
 public static int sum(int, int);
 public static int compareUnsigned(int, int);
 private static java.lang.String toStringUTF16(int, int);
 public static java.lang.String toUnsignedString(int, int);
 public static java.lang.String toUnsignedString(int);
 private static java.lang.String toUnsignedString0(int, int);
 private static void formatUnsignedInt(int, int, [B, int);
 private static void formatUnsignedIntUTF16(int, int, [B, int);
 public static int parseUnsignedInt(java.lang.String);
 public static int parseUnsignedInt(java.lang.CharSequence, int, int, int);
 public static int parseUnsignedInt(java.lang.String, int);
 public static java.lang.Integer getInteger(java.lang.String, java.lang.Integer);
 public static java.lang.Integer getInteger(java.lang.String, int);
 public static java.lang.Integer getInteger(java.lang.String);
 private static int parallelSuffix(int);
 public static java.lang.String toOctalString(int);
 public static java.lang.String toBinaryString(int);
 public static int highestOneBit(int);
 public static int lowestOneBit(int);
 public static int rotateLeft(int, int);
 public static int rotateRight(int, int);

 public static final int MIN_VALUE;
 public static final int MAX_VALUE;
 public static final java.lang.Class TYPE;
 static final [C digits;
 static final [B DigitTens;
 static final [B DigitOnes;
 static final [I sizeTable;
 private final int value;
 public static final int SIZE;
 public static final int BYTES;
 private static final long serialVersionUID;
}