---
title: "Лабораторная работа №2. Введение в язык обработки данных R. Анализ одномерных данных"
mainfont: Arial
monofont: Consolas
output:
  pdf_document: 
    latex_engine: lualatex
# Перед верстанием отчёта настоятельно рекомендуется изменить параметры. Более подробная информация по ним представлена в комментариях ниже.
params: 
    surname: "DUBOVSKIJ"
    name: "JAN"
    variant: "6"
    filename: "input.txt"
---

<!-- Ниже расположены два блока с программным кодом, который выводит фамилию и имя студента, а также номер варианта. Они определяются параметрами surname, name и variant, объявленными в преамбуле, расположенной выше. К параметрам в коде можно обращаться через конструкцию params$var, где var - название переменной --> 

<!-- Значения этих параметров можно поменять непосредственно в самом файле или используя опцию "Knit with Parameters..." -->

<!-- Параметр echo=FALSE означает, что в отчёте сам код представлен не будет, будет выведен только результат его выполнения (в данном случае - вывод имени студента и номера варианта) -->

**Студент:**

```{r, echo=FALSE}
cat(params$surname, params$name)
```

**Вариант**

```{r, echo=FALSE}
cat(params$variant)
```

## Чтение данных из файла

<!-- В коде ниже используется переменная params$filename, определённая в преамбуле. Можно её переопределить прямо в этом файле либо сверстать отчёт при помощи команды "Knit with Parameters...", указав в соответствующем поле имя файла или путь к нему. -->

<!-- В зависимости от структуры Вашего файла может понадобиться отредактировать код ниже -->

<!-- Вписал sort(d) для облегчения проверки вычислений -->

```{r}
dat <- read.table(file=params$filename, dec=",")
d <- dat[,1]
d
sort(d)
```

## Вычисление статистических характеристик

<!-- Расчитайте и выведите следующие статистические характеристики для Ваших данных -->

Среднее значение

```{r}
mean(d)

```

Дисперсия

```{r}
disp<-var(d)
disp

```

Среднее квадратическое отклонение

```{r}
sd(d)

```

Мода

```{r}
which.max(table(d))

```

Медиана

```{r}
median(d)

```

Коэффициент ассиметрии

```{r}
library(timeDate)
skewness(d)

```

Коэффициент эксцесса

```{r}
library(timeDate)
kurtosis(d)

```

<!-- Пожалуйста, укажите явно в тексте отчёта выбранный порядок (как вычисляется порядок усечённой средней, смотрите в лекции) -->

Усечённое среднее порядка 0.125

```{r}
truncated_mean <- mean(d, trim = 0.125)
truncated_mean

```

Коэффициент вариации

```{r}
the_coefficient_of_variation <- sqrt(disp) / mean(d) * 100
the_coefficient_of_variation

```

Относительное линейное отклонение

```{r}
mean_linear_deviation <- sum(abs(d - mean(d))) / length(d)
mean_linear_deviation
relative_linear_deviation <- mean_linear_deviation / mean(d) * 100
relative_linear_deviation

```
