---
title: "Лабораторная работа №4. Ряды динамики. Методы анализа основной тенденции (тренда) в рядах динамики"
mainfont: Arial
monofont: Consolas
output:
  pdf_document: 
    latex_engine: lualatex
# Перед верстанием отчёта настоятельно рекомендуется изменить параметры. Более подробная информация по ним представлена в комментариях ниже.
params: 
    surname: "Dubovskij"
    name: "Jan"
    variant: "10"
    filename: "input.txt"
---

<!-- Ниже расположены два блока с программным кодом, который выводит фамилию и имя студента, а также номер варианта. Они определяются параметрами surname, name и variant, объявленными в преамбуле, расположенной выше. К параметрам в коде можно обращаться через конструкцию params$var, где var - название переменной --> 

<!-- Значения этих параметров можно поменять непосредственно в самом файле или используя опцию "Knit with Parameters..." -->

<!-- Параметр echo=FALSE означает, что в отчёте сам код представлен не будет, будет выведен только результат его выполнения (в данном случае - вывод имени студента и номера варианта) -->

**Студент:**

```{r, echo=FALSE}
cat(params$surname, params$name)
```

**Вариант**

```{r, echo=FALSE}
cat(params$variant)
```

## Чтение данных из файла

<!-- Можно использовать параметр params$filename -->

```{r}
dat = read.table(file = "input.txt", dec = ",")

```

## Определение наличия тренда

<!-- Используйте критерий серий для выяснения наличия тренда в Вашем динамическом ряде.  -->

```{r}
myts = ts(dat[,1], start = c(2017,8), end = c(2018,7), frequency = 12)

#Средний уровень ряда динамики
mn = (sum(dat[,1]) - ((dat[1,1] + dat[length(dat),1]) / 2)) / (length(dat[,1]) - 1)

#Определяем наличие тренда
n <- length(dat[,1])
avery <-(sum(dat[1]) - dat[1,1]/2 - dat[1, length(dat[1])]/2)/(length(dat[,1])-1)
averr <- (length(dat[,1]) + 1)/2
sigmar <- sqrt(averr-1)/2
t <- 2
(averr+1 - t*sqrt(n-1))/2
avery
(averr+1 + t*sqrt(n-1))/2

```

**Вывод:** ... Поскольку 0.4333752<3.517318<7.066625, то нет наличие тренда в ряду динамики

## Сглаживание тренда

<!-- Проведите сглаживание Вашего ряда динамики методом трёхуровневой скользящей средней. Выведите полученный динамический ряд. -->

```{r}
library("pracma")
dat[,2] = movavg(dat[,1], 3, type = "s")
dat[2]

```

## Аналитическое выравнивание

<!-- Проведите сглаживание ряда динамики методом аналитического выравнивания по уравнению прямой y^ = a_0 + a_1 * t. Выведите полученный динамический ряд -->

```{r}
center = round(length(dat[,1]) / 2)

if(mod(length(dat[,1]), 2) == 1){
  dat[center,3] = 0
  for(i in 1:(center - 1)){
    dat[center - i,3] = -i
    dat[center + i,3] = i
  }
}else{
  for(i in 0:(center - 1)){
    dat[center - i,3] = -(1 + 2*i)
    dat[center + i + 1,3] = (1 + 2*i)
  }
}

a_0 = (sum(dat[,1]) / length(dat[,1]))
a_1 = 0
for (i in 1:length(dat[,1])) {
  a_1 = a_1 + dat[i,1]*dat[i,3]
}
a_1 = a_1 / sum((dat[3])^2)

for (i in 1:length(dat[,1])) {
  dat[i,4] = a_0 + dat[i,3]*a_1
}
dat[4]

```

Прогноз для следующего значения динамического ряда

<!-- Вычислите прогноз для следующего значения по построенной модели -->

```{r}
y_next = a_0 + a_1*((dat[length(dat[,3]), 3] - dat[length(dat[,3]) - 1, 3]) + dat[length(dat[,3]),3])
y_next
```

## График

<!-- Постройте на одном графике исходный и два сглаженных ряда -->

```{r dev=c('png')}
plot(myts, lwd = 3, col = "green", main="Time series", ylab = "Value")
lines(ts(dat[,2], start = c(2017,8), end = c(2018,7), frequency = 12), col = "red", lwd = 3)
lines(ts(dat[,4], start = c(2017,8), end = c(2018,7), frequency = 12), col = "blue", lwd = 3)
legend("bottomleft", legend = c("1", "2", "3"), fill = c("green", "red", "blue"))

```

