---
title: "Лабораторная работа №5. Кластерный анализ. Алгоритм K-means"
mainfont: Arial
monofont: Consolas
output:
  pdf_document: 
    latex_engine: lualatex
# Перед верстанием отчёта настоятельно рекомендуется изменить параметры. Более подробная информация по ним представлена в комментариях ниже.
params: 
    surname: "Dubovskij"
    name: "Pan"
    variant: "13  "
    filename: "input.txt"
---

<!-- Ниже расположены два блока с программным кодом, который выводит фамилию и имя студента, а также номер варианта. Они определяются параметрами surname, name и variant, объявленными в преамбуле, расположенной выше. К параметрам в коде можно обращаться через конструкцию params$var, где var - название переменной --> 

<!-- Значения этих параметров можно поменять непосредственно в самом файле или используя опцию "Knit with Parameters..." -->

<!-- Параметр echo=FALSE означает, что в отчёте сам код представлен не будет, будет выведен только результат его выполнения (в данном случае - вывод имени студента и номера варианта) -->

**Студент:**

```{r, echo=FALSE}
cat(params$surname, params$name)
```

**Вариант**

```{r, echo=FALSE}
cat(params$variant)
```

## Чтение данных из файла

<!-- Можно использовать параметр params$filename. Пожалуйста, выведите данные. -->

```{r}
dat = read.table(file = "input.txt", dec = ",")
dat

```

## Диаграмма рассеяния

```{r dev='png'}
plot(dat, type = "p", 
     main = "Диаграмма рассеивания", 
     xlab = "X", ylab = "Y",
     col = "red", pch = 20, cex = 2)

```

## Кластеризация на 2 кластера

<!-- Осуществить кластеризацию Ваших данных методом K-means. Определите характеристики кластеров: число элементов, центры. -->

```{r}
#Число кластеров = 2
cl = kmeans(scale(dat), 2)
#Число наблюдений
table(cl$cluster)

cl$centers

sapply(1:2, function(i) cl$centers[,i] * sd(dat[,i]) + mean(dat[,i]))

```

### Кластеры на графике рассеяния

<!-- Для обозначения элементов разных кластеров используйте маркеры разных цветов и/или формы -->

```{r dev='png'}
plot(dat, col = c("blue", "green")[cl$cluster], pch = 20, cex = 2, xlab = "X", ylab = "Y", main = "2 clusters")
legend("bottomleft", legend = c("1", "2"), fill = c("blue", "green"))

plot(dat, pch = (1:2)[cl$cluster], cex = 2, xlab = "X", ylab = "Y", main = "2 clusters")
legend("bottomleft", legend = c("1", "2"),pch = 1:2)


```

## Кластеризация на 3 кластера

<!-- Осуществить кластеризацию Ваших данных методом K-means. Определите характеристики кластеров: число элементов, центры. -->

```{r}
#Число кластеров = 3
cl = kmeans(scale(dat), 3)
#Число наблюдений
table(cl$cluster)

cl$centers

sapply(1:2, function(i) cl$centers[,i] * sd(dat[,i]) + mean(dat[,i]))

```

### Кластеры на графике рассеяния

<!-- Для обозначения элементов разных кластеров используйте маркеры разных цветов и/или формы -->

```{r dev='png'}
plot(dat, col = c("blue", "green", "red")[cl$cluster], pch = 20, cex = 2, xlab = "X", ylab = "Y", main = "3 clusters")
legend("bottomleft", legend = c("1", "2", "3"), fill = c("blue", "green", "red"))

plot(dat, pch = (1:3)[cl$cluster], cex = 2, xlab = "X", ylab = "Y", main = "3 clusters")
legend("bottomleft", legend = c("1", "2", "3"),pch = 1:3)


```
